
DROP TABLE IF EXISTS `countries`;

CREATE TABLE `countries` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `iso` varchar(2) NOT NULL,
  `iso3` varchar(3) NOT NULL,
  `capital` varchar(64) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `currency_name` varchar(64) NOT NULL,
  `creation_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `modification_at` DATETIME ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO countries
    (name, iso, iso3, capital, currency, currency_name)
VALUES
('Afghanistan','af','AFG','Kabul','AFN','Afghanistan Afghani'),
('Albania','al','ALB','Tirana','ALL','Albanian Lek'),
('Algeria','dz','DZA','Algiers','DZD','Algerian Dinar'),
('American Samoa','as','ASM','Pago Pago','USD','US Dollar'),
('Andorra','ad','AND','Andorra','EUR','Euro'),
('Angola','ao','AGO','Luanda','AOA','Angolan Kwanza'),
('Anguilla','ai','AIA','The Valley','XCD','East Caribbean Dollar'),
('Antarctica','aq','ATA','None','XCD','East Caribbean Dollar'),
('Antigua and Barbuda','ag','ATG','St. Johns','XCD','East Caribbean Dollar'),
('Argentina','ar','ARG','Buenos Aires','ARS','Argentine Peso'),
('Armenia','am','ARM','Yerevan','AMD','Armenian Dram'),
('Aruba','aw','ABW','Oranjestad','AWG','Aruban Guilder'),
('Australia','au','AUS','Canberra','AUD','Australian Dollar'),
('Austria','at','AUT','Vienna','EUR','Euro'),
('Azerbaijan','az','AZE','Baku','AZN','Azerbaijan New Manat'),
('Bahamas','bs','BHS','Nassau','BSD','Bahamian Dollar'),
('Bahrain','bh','BHR','Al-Manamah','BHD','Bahraini Dinar'),
('Bangladesh','bd','BGD','Dhaka','BDT','Bangladeshi Taka'),
('Barbados','bb','BRB','Bridgetown','BBD','Barbados Dollar'),
('Belarus','by','BLR','Minsk','BYR','Belarussian Ruble'),
('Belgium','be','BEL','Brussels','EUR','Euro'),
('Belize','bz','BLZ','Belmopan','BZD','Belize Dollar'),
('Benin','bj','BEN','Porto-Novo','XOF','CFA Franc BCEAO'),
('Bermuda','bm','BMU','Hamilton','BMD','Bermudian Dollar'),
('Bhutan','bt','BTN','Thimphu','BTN','Bhutan Ngultrum'),
('Bolivia','bo','BOL','La Paz','BOB','Boliviano'),
('Bonaire, Sint Eustatius and Saba','bq','BES','Kralendijk','',''),
('Bosnia-Herzegovina','ba','BIH','Sarajevo','BAM','Marka'),
('Botswana','bw','BWA','Gaborone','BWP','Botswana Pula'),
('Bouvet Island','bv','BVT','None','NOK','Norwegian Krone'),
('Brazil','br','BRA','Brasilia','BRL','Brazilian Real'),
('British Indian Ocean Territory','io','IOT','None','USD','US Dollar'),
('Brunei Darussalam','bn','BRN','Bandar Seri Begawan','BND','Brunei Dollar'),
('Bulgaria','bg','BGR','Sofia','BGN','Bulgarian Lev'),
('Burkina Faso','bf','BFA','Ouagadougou','XOF','CFA Franc BCEAO'),
('Burundi','bi','BDI','Bujumbura','BIF','Burundi Franc'),
('Cabo Verde','cv','CPV','Praia','CVE','Cape Verde Escudo'),
('Cambodia','kh','KHM','Phnom Penh','KHR','Kampuchean Riel'),
('Cameroon','cm','CMR','Yaounde','XAF','CFA Franc BEAC'),
('Canada','ca','CAN','Ottawa','CAD','Canadian Dollar'),
('Cayman Islands','ky','CYM','Georgetown','KYD','Cayman Islands Dollar'),
('Central African Republic','cf','CAF','Bangui','XAF','CFA Franc BEAC'),
('Chad','td','TCD','N`Djamena','XAF','CFA Franc BEAC'),
('Chile','cl','CHL','Santiago','CLP','Chilean Peso'),
('China','cn','CHN','Beijing','CNY','Yuan Renminbi'),
('Christmas Island','cx','CXR','The Settlement','AUD','Australian Dollar'),
('Cocos (Keeling) Islands','cc','CCK','West Island','AUD','Australian Dollar'),
('Colombia','co','COL','Bogota','COP','Colombian Peso'),
('Comoros','km','COM','Moroni','KMF','Comoros Franc'),
('Congo','cg','COG','Brazzaville','XAF','CFA Franc BEAC'),
('Congo, Dem. Republic','cd','COD','Kinshasa','CDF','Francs'),
('Cook Islands','ck','COK','Avarua','NZD','New Zealand Dollar'),
('Costa Rica','cr','CRI','San Jose','CRC','Costa Rican Colon'),
('Croatia','hr','HRV','Zagreb','HRK','Croatian Kuna'),
('Cuba','cu','CUB','Havana','CUP','Cuban Peso'),
('Curaçao','cw','CUW','Willemstad','ANG',''),
('Cyprus','cy','CYP','Nicosia','EUR','Euro'),
('Czechia','cz','CZE','Prague','CZK','Czech Koruna'),
('Côte d`Ivoire','ci','CIV','Abidjan','XOF','CFA Franc BCEAO'),
('Denmark','dk','DNK','Copenhagen','DKK','Danish Krone'),
('Djibouti','dj','DJI','Djibouti','DJF','Djibouti Franc'),
('Dominica','dm','DMA','Roseau','XCD','East Caribbean Dollar'),
('Dominican Republic','do','DOM','Santo Domingo','DOP','Dominican Peso'),
('Ecuador','ec','ECU','Quito','ECS','Ecuador Sucre'),
('Egypt','eg','EGY','Cairo','EGP','Egyptian Pound'),
('El Salvador','sv','SLV','San Salvador','SVC','El Salvador Colon'),
('Equatorial Guinea','gq','GNQ','Malabo','XAF','CFA Franc BEAC'),
('Eritrea','er','ERI','Asmara','ERN','Eritrean Nakfa'),
('Estonia','ee','EST','Tallinn','EUR','Euro'),
('Eswatini','sz','SWZ','Mbabane','SZL','Swaziland Lilangeni'),
('Ethiopia','et','ETH','Addis Ababa','ETB','Ethiopian Birr'),
('European Union','eu','INT','Brussels','EUR','Euro'),
('Falkland Islands (Malvinas)','fk','FLK','Stanley','FKP','Falkland Islands Pound'),
('Faroe Islands','fo','FRO','Torshavn','DKK','Danish Krone'),
('Fiji','fj','FJI','Suva','FJD','Fiji Dollar'),
('Finland','fi','FIN','Helsinki','EUR','Euro'),
('France','fr','FRA','Paris','EUR','Euro'),
('French Guiana','gf','GUF','Cayenne','EUR','Euro'),
('French Polynesia','pf','PYF','Papeete','XPF','CFP Franc'),
('French Southern Territories','tf','ATF','None','EUR','Euro'),
('Gabon','ga','GAB','Libreville','XAF','CFA Franc BEAC'),
('Gambia','gm','GMB','Banjul','GMD','Gambian Dalasi'),
('Georgia','ge','GEO','Tbilisi','GEL','Georgian Lari'),
('Germany','de','DEU','Berlin','EUR','Euro'),
('Ghana','gh','GHA','Accra','GHS','Ghanaian Cedi'),
('Gibraltar','gi','GIB','Gibraltar','GIP','Gibraltar Pound'),
('Greece','gr','GRC','Athens','EUR','Euro'),
('Greenland','gl','GRL','Godthab','DKK','Danish Krone'),
('Grenada','gd','GRD','St. George`s','XCD','East Carribean Dollar'),
('Guadeloupe (French)','gp','GLP','Basse-Terre','EUR','Euro'),
('Guam (USA)','gu','GUM','Agana','USD','US Dollar'),
('Guatemala','gt','GTM','Guatemala City','GTQ','Guatemalan Quetzal'),
('Guernsey','gg','GGY','St. Peter Port','GGP','Pound Sterling'),
('Guinea','gn','GIN','Conakry','GNF','Guinea Franc'),
('Guinea Bissau','gw','GNB','Bissau','GWP','Guinea-Bissau Peso'),
('Guyana','gy','GUY','Georgetown','GYD','Guyana Dollar'),
('Haiti','ht','HTI','Port-au-Prince','HTG','Haitian Gourde'),
('Heard Island and McDonald Islands','hm','HMD','None','AUD','Australian Dollar'),
('Holy See','va','VAT','Vatican City','EUR','Euro'),
('Honduras','hn','HND','Tegucigalpa','HNL','Honduran Lempira'),
('Hong Kong','hk','HKG','Victoria','HKD','Hong Kong Dollar'),
('Hungary','hu','HUN','Budapest','HUF','Hungarian Forint'),
('Iceland','is','ISL','Reykjavik','ISK','Iceland Krona'),
('India','in','IND','New Delhi','INR','Indian Rupee'),
('Indonesia','id','IDN','Jakarta','IDR','Indonesian Rupiah'),
('Iran','ir','IRN','Tehran','IRR','Iranian Rial'),
('Iraq','iq','IRQ','Baghdad','IQD','Iraqi Dinar'),
('Ireland','ie','IRL','Dublin','EUR','Euro'),
('Isle of Man','im','IMN','Douglas','GBP','Pound Sterling'),
('Israel','il','ISR','Jerusalem','ILS','Israeli New Shekel'),
('Italy','it','ITA','Rome','EUR','Euro'),
('Jamaica','jm','JAM','Kingston','JMD','Jamaican Dollar'),
('Japan','jp','JPN','Tokyo','JPY','Japanese Yen'),
('Jersey','je','JEY','Saint Helier','GBP','Pound Sterling'),
('Jordan','jo','JOR','Amman','JOD','Jordanian Dinar'),
('Kazakhstan','kz','KAZ','Astana','KZT','Kazakhstan Tenge'),
('Kenya','ke','KEN','Nairobi','KES','Kenyan Shilling'),
('Kiribati','ki','KIR','Tarawa','AUD','Australian Dollar'),
('Korea-North','kp','PRK','Pyongyang','KPW','North Korean Won'),
('Korea-South','kr','KOR','Seoul','KRW','Korean Won'),
('Kuwait','kw','KWT','Kuwait City','KWD','Kuwaiti Dinar'),
('Kyrgyzstan','kg','KGZ','Bishkek','KGS','Som'),
('Laos','la','LAO','Vientiane','LAK','Lao Kip'),
('Latvia','lv','LVA','Riga','LVL','Latvian Lats'),
('Lebanon','lb','LBN','Beirut','LBP','Lebanese Pound'),
('Lesotho','ls','LSO','Maseru','LSL','Lesotho Loti'),
('Liberia','lr','LBR','Monrovia','LRD','Liberian Dollar'),
('Libya','ly','LBY','Tripoli','LYD','Libyan Dinar'),
('Liechtenstein','li','LIE','Vaduz','CHF','Swiss Franc'),
('Lithuania','lt','LTU','Vilnius','LTL','Lithuanian Litas'),
('Luxembourg','lu','LUX','Luxembourg','EUR','Euro'),
('Macao','mo','MAC','Macau','MOP','Macau Pataca'),
('Madagascar','mg','MDG','Antananarivo','MGF','Malagasy Franc'),
('Malawi','mw','MWI','Lilongwe','MWK','Malawi Kwacha'),
('Malaysia','my','MYS','Kuala Lumpur','MYR','Malaysian Ringgit'),
('Maldives','mv','MDV','Male','MVR','Maldive Rufiyaa'),
('Mali','ml','MLI','Bamako','XOF','CFA Franc BCEAO'),
('Malta','mt','MLT','Valletta','EUR','Euro'),
('Marshall Islands','mh','MHL','Majuro','USD','US Dollar'),
('Martinique (French)','mq','MTQ','Fort-de-France','EUR','Euro'),
('Mauritania','mr','MRT','Nouakchott','MRO','Mauritanian Ouguiya'),
('Mauritius','mu','MUS','Port Louis','MUR','Mauritius Rupee'),
('Mayotte','yt','MYT','Dzaoudzi','EUR','Euro'),
('Mexico','mx','MEX','Mexico City','MXN','Mexican Nuevo Peso'),
('Micronesia','fm','FSM','Palikir','USD','US Dollar'),
('Moldova','md','MDA','Kishinev','MDL','Moldovan Leu'),
('Monaco','mc','MCO','Monaco','EUR','Euro'),
('Mongolia','mn','MNG','Ulan Bator','MNT','Mongolian Tugrik'),
('Montenegro','me','MNE','Podgorica','EUR','Euro'),
('Montserrat','ms','MSR','Plymouth','XCD','East Caribbean Dollar'),
('Morocco','ma','MAR','Rabat','MAD','Moroccan Dirham'),
('Mozambique','mz','MOZ','Maputo','MZN','Mozambique Metical'),
('Myanmar','mm','MMR','Naypyidaw','MMK','Myanmar Kyat'),
('Namibia','na','NAM','Windhoek','NAD','Namibian Dollar'),
('Nauru','nr','NRU','Yaren','AUD','Australian Dollar'),
('Nepal','np','NPL','Kathmandu','NPR','Nepalese Rupee'),
('Netherlands','nl','NLD','Amsterdam','EUR','Euro'),
('New Caledonia (French)','nc','NCL','Noumea','XPF','CFP Franc'),
('New Zealand','nz','NZL','Wellington','NZD','New Zealand Dollar'),
('Nicaragua','ni','NIC','Managua','NIO','Nicaraguan Cordoba Oro'),
('Niger','ne','NER','Niamey','XOF','CFA Franc BCEAO'),
('Nigeria','ng','NGA','Lagos','NGN','Nigerian Naira'),
('Niue','nu','NIU','Alofi','NZD','New Zealand Dollar'),
('Norfolk Island','nf','NFK','Kingston','AUD','Australian Dollar'),
('North Macedonia','mk','MKD','Skopje','MKD','Denar'),
('Northern Mariana Islands','mp','MNP','Saipan','USD','US Dollar'),
('Norway','no','NOR','Oslo','NOK','Norwegian Krone'),
('Oman','om','OMN','Muscat','OMR','Omani Rial'),
('Pakistan','pk','PAK','Islamabad','PKR','Pakistan Rupee'),
('Palau','pw','PLW','Koror','USD','US Dollar'),
('Panama','pa','PAN','Panama City','PAB','Panamanian Balboa'),
('Papua New Guinea','pg','PNG','Port Moresby','PGK','Papua New Guinea Kina'),
('Paraguay','py','PRY','Asuncion','PYG','Paraguay Guarani'),
('Peru','pe','PER','Lima','PEN','Peruvian Nuevo Sol'),
('Philippines','ph','PHL','Manila','PHP','Philippine Peso'),
('Pitcairn Island','pn','PCN','Adamstown','NZD','New Zealand Dollar'),
('Poland','pl','POL','Warsaw','PLN','Polish Zloty'),
('Portugal','pt','PRT','Lisbon','EUR','Euro'),
('Puerto Rico','pr','PRI','San Juan','USD','US Dollar'),
('Qatar','qa','QAT','Doha','QAR','Qatari Rial'),
('Reunion (French)','re','REU','Saint-Denis','EUR','Euro'),
('Romania','ro','ROU','Bucharest','RON','Romanian New Leu'),
('Russia','ru','RUS','Moscow','RUB','Russian Ruble'),
('Rwanda','rw','RWA','Kigali','RWF','Rwanda Franc'),
('Saint Barthélemy','bl','BLM','Gustavia','',''),
('Saint Helena','sh','SHN','Jamestown','SHP','St. Helena Pound'),
('Saint Kitts & Nevis Anguilla','kn','KNA','Basseterre','XCD','East Caribbean Dollar'),
('Saint Lucia','lc','LCA','Castries','XCD','East Caribbean Dollar'),
('Saint Martin (French part)','mf','MAF','Marigot','',''),
('Saint Pierre and Miquelon','pm','SPM','St. Pierre','EUR','Euro'),
('Saint Vincent & Grenadines','vc','VCT','Kingstown','XCD','East Caribbean Dollar'),
('Samoa','ws','WSM','Apia','WST','Samoan Tala'),
('San Marino','sm','SMR','San Marino','EUR','Euro'),
('Sao Tome and Principe','st','STP','Sao Tome','STD','Dobra'),
('Saudi Arabia','sa','SAU','Riyadh','SAR','Saudi Riyal'),
('Senegal','sn','SEN','Dakar','XOF','CFA Franc BCEAO'),
('Serbia','rs','SRB','Belgrade','RSD','Dinar'),
('Seychelles','sc','SYC','Victoria','SCR','Seychelles Rupee'),
('Sierra Leone','sl','SLE','Freetown','SLL','Sierra Leone Leone'),
('Singapore','sg','SGP','Singapore','SGD','Singapore Dollar'),
('Sint Maarten (Dutch part)','sx','SXM','Philipsburg','',''),
('Slovakia','sk','SVK','Bratislava','EUR','Euro'),
('Slovenia','si','SVN','Ljubljana','EUR','Euro'),
('Solomon Islands','sb','SLB','Honiara','SBD','Solomon Islands Dollar'),
('Somalia','so','SOM','Mogadishu','SOS','Somali Shilling'),
('South Africa','za','ZAF','Pretoria','ZAR','South African Rand'),
('South Georgia & South Sandwich Islands','gs','SGS','None','GBP','Pound Sterling'),
('South Sudan','ss','SSD','Ramciel','SSP','South Sudan Pound'),
('Spain','es','ESP','Madrid','EUR','Euro'),
('Sri Lanka','lk','LKA','Colombo','LKR','Sri Lanka Rupee'),
('Sudan','sd','SDN','Khartoum','SDG','Sudanese Pound'),
('Suriname','sr','SUR','Paramaribo','SRD','Surinam Dollar'),
('Svalbard and Jan Mayen Islands','sj','SJM','Longyearbyen','NOK','Norwegian Krone'),
('Sweden','se','SWE','Stockholm','SEK','Swedish Krona'),
('Switzerland','ch','CHE','Bern','CHF','Swiss Franc'),
('Syria','sy','SYR','Damascus','SYP','Syrian Pound'),
('Taiwan','tw','TWN','Taipei','TWD','Taiwan Dollar'),
('Tajikistan','tj','TJK','Dushanbe','TJS','Tajik Somoni'),
('Tanzania','tz','TZA','Dodoma','TZS','Tanzanian Shilling'),
('Thailand','th','THA','Bangkok','THB','Thai Baht'),
('Timor-Leste','tl','TLS','Dili','',''),
('Togo','tg','TGO','Lome','XOF','CFA Franc BCEAO'),
('Tokelau','tk','TKL','None','NZD','New Zealand Dollar'),
('Tonga','to','TON','Nuku`alofa','TOP','Tongan Pa`anga'),
('Trinidad and Tobago','tt','TTO','Port of Spain','TTD','Trinidad and Tobago Dollar'),
('Tunisia','tn','TUN','Tunis','TND','Tunisian Dollar'),
('Turkey','tr','TUR','Ankara','TRY','Turkish Lira'),
('Turkmenistan','tm','TKM','Ashgabat','TMT','Manat'),
('Turks and Caicos Islands','tc','TCA','Grand Turk','USD','US Dollar'),
('Tuvalu','tv','TUV','Funafuti','AUD','Australian Dollar'),
('USA','us','USA','Washington','USD','US Dollar'),
('USA Minor Outlying Islands','um','UMI','None','USD','US Dollar'),
('Uganda','ug','UGA','Kampala','UGX','Uganda Shilling'),
('Ukraine','ua','UKR','Kiev','UAH','Ukraine Hryvnia'),
('United Arab Emirates','ae','ARE','Abu Dhabi','AED','Arab Emirates Dirham'),
('United Kingdom (Great Britain and N. Ireland)','gb','GBR','London','GBP','Pound Sterling'),
('Uruguay','uy','URY','Montevideo','UYU','Uruguayan Peso'),
('Uzbekistan','uz','UZB','Tashkent','UZS','Uzbekistan Sum'),
('Vanuatu','vu','VUT','Port Vila','VUV','Vanuatu Vatu'),
('Venezuela','ve','VEN','Caracas','VEF','Venezuelan Bolivar'),
('Vietnam','vn','VNM','Hanoi','VND','Vietnamese Dong'),
('Virgin Islands (British)','vg','VGB','Road Town','USD','US Dollar'),
('Virgin Islands (USA)','vi','VIR','Charlotte Amalie','USD','US Dollar'),
('Wallis and Futuna Islands','wf','WLF','Mata-Utu','XPF','CFP Franc'),
('Western Sahara','eh','ESH','El Aaiun','MAD','Moroccan Dirham'),
('Yemen','ye','YEM','San`a','YER','Yemeni Rial'),
('Zambia','zm','ZMB','Lusaka','ZMW','Zambian Kwacha'),
('Zimbabwe','zw','ZWE','Harare','ZWD','Zimbabwe Dollar,')





